name: Bundle Sizes

on:
  push:
    branches: [main]

jobs:
  benchmark:
    name: Bundle Sizes Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: configure npm auth token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: npm install
        run: npm install
      - run: npm run build-bundle-sizes
      - run: brotli ./out/*

      # Builds bundles then measures bundles sizes and stores them to a file
      - name: Measure bundles
        run: node perf/bundle-sizes --bundles replicache.js replicache.js.br replicache.mjs replicache.mjs.br replicache.min.mjs replicache.min.mjs.br | tee bundle-sizes.json

      # install above may have modified package-lock, in which case
      # rhysd/github-action-benchmark@v1 will error when trying to switch
      # branches to commit the new data to the gh-pages branch
      - run: git restore package-lock.json

      # Run `github-action-benchmark` action
      - name: Store bundle size
        uses: rhysd/github-action-benchmark@v1
        with:
          name: 'Bundle Sizes'
          tool: 'customSmallerIsBetter'
          output-file-path: bundle-sizes.json
          fail-on-alert: true
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          benchmark-data-dir-path: bundle-sizes
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
