name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: microsoft/playwright-github-action@v1
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run check-format
      - run: npm run lint
      - run: npm test
