name: Perf Test V2

on:
  push:
    branches: [main]

jobs:
  benchmark:
    name: Performance regression check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Clear out potential user data dirs left over from previous failures.
      - run: rm -rf /tmp/replicache-playwright-*
      - name: configure npm auth token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run build-perf

      # Run benchmark and stores the output to a file
      - name: Run benchmark
        run: node perf/runner.js --format=json | tee perf-v2-output.json
        shell: bash

      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          # What benchmark tool the output.json came from
          tool: 'customSmallerIsBetter'
          # Where the output from the benchmark tool is stored
          output-file-path: perf-v2-output.json
          # Workflow will fail when an alert happens
          fail-on-alert: true
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          benchmark-data-dir-path: perf-v2
          auto-push: true
          alert-threshold: '130%'
          comment-on-alert: true
